apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: react-microk8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      imagePullSecrets:
        - name: gcr-auth
      containers:
        - name: react-container
          image: asia-docker.pkg.dev/silken-oxygen-454215-v6/react-app/react-docker@sha256:73741414154b12d0c421271fd490ce14aa8114d47a8bf7c0a2efa3c4754dfde6
          ports:
            - containerPort: 80

